# Generated by Django 3.2 on 2021-06-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokerPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('balance', models.IntegerField(max_length=6)),
                ('history', models.TextField(max_length=512)),
            ],
        ),
    ]
