# Generated by Django 3.2 on 2021-06-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerplayer',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
