# Generated by Django 3.2 on 2021-06-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0002_alter_pokerplayer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokerplayer',
            name='history',
            field=models.TextField(blank=True, max_length=512),
        ),
    ]
