# Generated by Django 4.2 on 2023-07-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poker', '0003_alter_pokerplayer_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PokerSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pokerplayer',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='pokerplayer',
            name='history',
        ),
        migrations.CreateModel(
            name='PokerPlayerGamePerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chips', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.pokergame')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.pokerplayer')),
            ],
        ),
        migrations.AddField(
            model_name='pokergame',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker.pokerseason'),
        ),
    ]
