# Generated by Django 2.2.5 on 2021-02-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CsgoPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('elo', models.IntegerField(default=1500)),
                ('kills', models.IntegerField(default=0)),
                ('assists', models.IntegerField(default=0)),
                ('deaths', models.IntegerField(default=0)),
                ('playes_matches', models.IntegerField(default=0)),
            ],
        ),
    ]
