# Generated by Django 2.2.5 on 2021-03-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csgoplayer',
            name='playes_matches',
        ),
        migrations.AddField(
            model_name='csgoplayer',
            name='played_matches',
            field=models.IntegerField(default=0),
        ),
    ]
