# Generated by Django 2.2.5 on 2021-03-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0002_auto_20210304_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='csgoplayer',
            name='steam_id',
            field=models.CharField(default='AddSteamID', max_length=18),
            preserve_default=False,
        ),
    ]
