# Generated by Django 4.2 on 2023-07-14 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0004_csmap_csmatch_csmode_csplayer_csplayermatch_csrank_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='csplayer',
            name='elo',
        ),
        migrations.CreateModel(
            name='CSPlayerSeasonElo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elo', models.IntegerField(default=1500)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.csplayer')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='csgo.csseason')),
            ],
        ),
    ]
