# Generated by Django 4.2 on 2023-07-14 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0006_alter_csplayerseasonelo_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csmap',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='csmode',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='csplayer',
            name='steam_id',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='csrank',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='csplayermatch',
            unique_together={('player', 'match')},
        ),
    ]
