# Generated by Django 4.2 on 2023-07-17 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgo', '0007_alter_csmap_name_alter_csmode_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='csplayermatch',
            name='adr',
            field=models.IntegerField(default=0),
        ),
    ]
